name: Cypress Czy odpali testy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Chrome
        uses: cypress-io/github-action@v5
        timeout-minutes: 10
        with:
          build: npm run e2e:chrome
          start: npm start
          browser: chrome
