name: Czy odpali testy

on: push

jobs:
  chrome:
    runs-on: ubuntu-22.04
    steps:
      - name: Odpala cyprss
        uses: cypress-io/github-action@v5
        timeout-minutes: 10
        with:
          build: npm run build
          start: npm run e2e
          browser: chrome
